"""Plan-task reviewer quorum validation (Phase 3.1).

`plan_task` uses majority-vote coordination (REVISE_PLAN at >=2 FAILs). That
is only sound when there are at least 2 distinct reviewer models and every
configured model appears at most once. Before v4.39.0, the one-model-padded
and duplicate-model configurations passed silently — the check added in this
module makes both cases explicit errors pointing at `NEILA_REVIEW_MODELS`.
"""

from __future__ import annotations

import asyncio
import pathlib
import unittest
from unittest.mock import MagicMock, patch


def _make_ctx() -> MagicMock:
    ctx = MagicMock()
    ctx.repo_dir = pathlib.Path(".")
    ctx.drive_root = pathlib.Path(".")
    ctx.emit_progress_fn = MagicMock()
    return ctx


class TestPlanReviewerQuorum(unittest.IsolatedAsyncioTestCase):
    """Cover the three contract cases spelled out in the task:

    * 1 model → error
    * duplicates (e.g. ["a", "a", "b"]) → error
    * 2+ unique ([a, b, c]) → proceeds past the quorum gate
    """

    async def _run_with_models(self, models, env_raw=None):
        """Invoke `_run_plan_review_async` with injected user-configured
        reviewer list. Patches BOTH `_cfg.get_review_models` (resolved count)
        AND the `NEILA_REVIEW_MODELS` env var (raw user intent for the
        duplicate check) so both quorum branches see consistent data.

        `env_raw` defaults to the comma-joined `models` — the common case
        where resolved and raw match. Pass `env_raw=""` or a different CSV
        to exercise the direct-provider-fallback scenario where the resolved
        list is generated by `config.get_review_models` (not user-authored)
        and the duplicate check must skip.
        """
        import os as _os
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()
        raw_value = env_raw if env_raw is not None else ",".join(models)

        with (
            patch.dict(_os.environ, {"NEILA_REVIEW_MODELS": raw_value}, clear=False),
            patch.object(_cfg, "get_review_models", return_value=list(models)),
            # `_get_review_models` adds the pad-to-3 behaviour the parallel
            # runner expects; stub it to return the padded mirror so the
            # downstream path is consistent when the quorum gate passes.
            patch.object(
                pr, "_get_review_models",
                return_value=list(models) + [models[-1]] * (3 - len(models))
                if models else [],
            ),
            # Stub the prompt-building dependencies so we don't need a real
            # repo layout for the quorum check. The quorum gate fires BEFORE
            # the prompt is assembled; the patches here are only defensive
            # so tests do not touch the disk if the gate ever moves.
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("neila.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            return await pr._run_plan_review_async(ctx, "plan", "goal", [])

    async def test_single_model_returns_error(self):
        result = await self._run_with_models(["only/one"])
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("at least 2 unique reviewer models", result)
        self.assertIn("NEILA_REVIEW_MODELS", result)

    async def test_duplicates_in_list_returns_error(self):
        """User-authored duplicates in `NEILA_REVIEW_MODELS` (e.g.
        `"a,a,b"`) must error. The check runs against the raw env var,
        NOT the resolved `config.get_review_models()` output, so server-
        generated `[main, light, light]` fallback is not mis-flagged."""
        result = await self._run_with_models(
            ["a", "a", "b"], env_raw="a,a,b",
        )
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("duplicate", result.lower())
        self.assertIn("['a']", result)  # duplicates list must include "a"
        self.assertIn("NEILA_REVIEW_MODELS", result)

    async def test_two_unique_models_no_duplicates_proceeds(self):
        result = await self._run_with_models(["a", "b"])
        # Must NOT return the quorum error; the call reaches the reviewer-
        # aggregation path (stubbed) and produces the standard output.
        self.assertNotIn("at least 2 unique", result)
        self.assertNotIn("duplicate reviewer models", result)

    async def test_three_unique_models_proceeds(self):
        """The default shipped config (3 distinct OpenRouter models) must pass."""
        result = await self._run_with_models([
            "openai/gpt-5.5",
            "google/gemini-3.1-pro-preview",
            "anthropic/claude-opus-4.6",
        ])
        self.assertNotIn("at least 2 unique", result)
        self.assertNotIn("duplicate reviewer models", result)

    async def test_all_same_model_three_times_returns_error(self):
        """All-identical reviewer list is unsound. When the raw env var
        reads `"x,x,x"` the duplicate branch fires first (more actionable —
        points at the duplicated entry). Either branch would be a correct
        rejection; pin the current behaviour so it stays deterministic."""
        result = await self._run_with_models(
            ["x", "x", "x"], env_raw="x,x,x",
        )
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("duplicate", result.lower())
        self.assertIn("['x']", result)

    async def test_error_message_lists_exact_duplicates_sorted(self):
        """Regression: the duplicates-list in the error is sorted() so the
        message is deterministic regardless of input order."""
        result = await self._run_with_models(
            ["c", "b", "a", "b", "c"], env_raw="c,b,a,b,c",
        )
        # Both b and c appear more than once → reported in sorted order.
        self.assertIn("['b', 'c']", result)


class TestQuorumGateOrdering(unittest.IsolatedAsyncioTestCase):
    """The quorum gate must fire BEFORE expensive work (prompt assembly,
    repo pack build, estimate_tokens). Otherwise the error comes late and
    we waste I/O on every mis-configured call."""

    async def test_gate_fires_before_prompt_assembly(self):
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()

        prompt_build_calls = {"n": 0}

        def _spy_pack(*args, **kwargs):
            prompt_build_calls["n"] += 1
            return ("pack", [])

        with (
            # User configured only 1 model → quorum gate must fire.
            patch.object(_cfg, "get_review_models", return_value=["x"]),
            patch.object(pr, "_get_review_models", return_value=["x", "x", "x"]),
            patch.object(pr, "build_full_repo_pack", side_effect=_spy_pack),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertTrue(result.startswith("ERROR"))
        self.assertEqual(
            prompt_build_calls["n"], 0,
            "repo-pack build ran despite the quorum gate firing — expensive work "
            "should never happen when models are misconfigured",
        )


class TestNoDuplicateVotesInActualRun(unittest.IsolatedAsyncioTestCase):
    """After the quorum gate passes, the parallel run must use UNIQUE reviewers
    only — the pad-to-3 output from `_get_review_models` would let the same
    model cast two votes (e.g. `"a,b"` → `[a, b, b]`). The v4.39.0 fix drops
    those padding duplicates before the parallel run so majority-vote stays
    sound. Regression guard for Pass-2 review finding.
    """

    async def test_two_unique_config_runs_two_reviewers_not_three(self):
        """`NEILA_REVIEW_MODELS="a,b"` must invoke `_query_reviewer` exactly
        twice (once per unique model), not three times."""
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()
        call_log: list[str] = []

        def _spy_reviewer(ctx_inner, model, *args, **kwargs):
            call_log.append(model)
            return {
                "model": model, "text": "AGGREGATE: GREEN", "error": None,
                "tokens_in": 0, "tokens_out": 0,
            }

        with (
            patch.object(_cfg, "get_review_models",
                         return_value=["model/a", "model/b"]),
            patch.object(pr, "_get_review_models",
                         return_value=["model/a", "model/b", "model/b"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("neila.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(pr, "_query_reviewer", side_effect=_spy_reviewer),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        assert "ERROR" not in result or "Plan Review Results" in result, (
            f"Unexpected error path: {result[:300]}"
        )
        assert call_log == ["model/a", "model/b"], (
            f"Expected exactly 2 unique reviewer invocations, got {call_log}. "
            "Padding duplicates must not cause the same model to vote twice."
        )

    async def test_three_unique_config_runs_three_reviewers(self):
        """3 unique configured reviewers → 3 unique invocations (no change)."""
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()
        call_log: list[str] = []

        def _spy_reviewer(ctx_inner, model, *args, **kwargs):
            call_log.append(model)
            return {
                "model": model, "text": "AGGREGATE: GREEN", "error": None,
                "tokens_in": 0, "tokens_out": 0,
            }

        with (
            patch.object(_cfg, "get_review_models",
                         return_value=["a", "b", "c"]),
            patch.object(pr, "_get_review_models",
                         return_value=["a", "b", "c"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("neila.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(pr, "_query_reviewer", side_effect=_spy_reviewer),
        ):
            await pr._run_plan_review_async(ctx, "plan", "goal", [])

        assert call_log == ["a", "b", "c"], call_log


class TestQuorumWithRealEnvVar(unittest.IsolatedAsyncioTestCase):
    """Integration test that exercises the real `NEILA_REVIEW_MODELS` env-var
    → `_get_review_models` → padding → quorum-check chain without patching
    `_get_review_models`. Guards against the v4.39.0 regression where padding
    made user-authored 2-unique configurations trip the quorum gate."""

    async def _run_with_env(self, models_env: str) -> str:
        """Run the full plan-review pipeline with `NEILA_REVIEW_MODELS`
        set to the given CSV; downstream plumbing is stubbed but the
        `_get_review_models` path runs for real."""
        import os as _os
        from neila.tools import plan_review as pr

        ctx = _make_ctx()

        with (
            patch.dict(_os.environ, {"NEILA_REVIEW_MODELS": models_env}, clear=False),
            # Leave `_get_review_models` / `_cfg.get_review_models` unmocked so
            # the real parse + pad logic runs. Stub out prompt assembly and the
            # LLM call.
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("neila.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            return await pr._run_plan_review_async(ctx, "plan", "goal", [])

    async def test_two_unique_env_models_pass_quorum_gate(self):
        """Regression for v4.39.0 finding: `NEILA_REVIEW_MODELS="a,b"`
        expands to `[a, b, b]` after padding. The quorum check must see the
        USER intent (2 unique) rather than the padded reality, and let the
        review proceed."""
        result = await self._run_with_env("openrouter/a,openrouter/b")
        # Must NOT hit the quorum error — user configured 2 unique reviewers.
        self.assertNotIn("at least 2 unique reviewer models", result,
            f"2-unique env config was incorrectly rejected: {result[:500]}")
        self.assertNotIn("duplicate reviewer models", result,
            f"Padded duplicates tripped the user-duplicates branch: {result[:500]}")

    async def test_three_unique_env_models_pass_quorum_gate(self):
        """Shipped default: 3 distinct OpenRouter models via env must pass."""
        result = await self._run_with_env(
            "openai/gpt-5.5,google/gemini-3.1-pro-preview,anthropic/claude-opus-4.6"
        )
        self.assertNotIn("at least 2 unique reviewer models", result)
        self.assertNotIn("duplicate reviewer models", result)

    async def test_single_env_model_returns_error(self):
        """`NEILA_REVIEW_MODELS="only/one"` → padded to `[only/one]*3`
        → 1 unique → quorum error. The error message must point at
        `NEILA_REVIEW_MODELS`, not just the padded list."""
        result = await self._run_with_env("only/one")
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("at least 2 unique reviewer models", result)
        self.assertIn("NEILA_REVIEW_MODELS", result)

    async def test_user_authored_duplicates_in_env_returns_error(self):
        """`NEILA_REVIEW_MODELS="a,a,b"` is a user error — the list already
        has 3 entries (no padding applied), and "a" appears twice. Must
        trip the duplicates branch with a sorted list of duplicates."""
        result = await self._run_with_env("dup/x,dup/x,other/y")
        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("duplicate reviewer models", result)
        self.assertIn("dup/x", result)


class TestDirectProviderFallbackAccepted(unittest.IsolatedAsyncioTestCase):
    """When `config.get_review_models()` emits `[main, light, light]` as the
    direct-provider fallback (v4.39.0 quorum-safe shape), `_run_plan_review_async`
    MUST accept it — the duplicated `light` entries are server-generated,
    not user-authored, and the raw env var either points at a non-matching
    OpenRouter-style list or is empty. Regression for Pass-7 review finding
    that the duplicate-check had been validating against the resolved config
    result instead of the raw user intent."""

    async def test_direct_provider_anthropic_fallback_passes_quorum(self):
        import os as _os
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()

        # User has a non-matching OpenRouter-style reviewer list but only
        # Anthropic key is present. `config.get_review_models` will fall back
        # to `[main, light, light]`.
        env = {
            "NEILA_REVIEW_MODELS": (
                "openai/gpt-5.5,google/gemini-3.1-pro-preview,"
                "anthropic/claude-opus-4.6"
            ),
            "NEILA_MODEL": "anthropic::claude-opus-4-6",
            "NEILA_MODEL_LIGHT": "anthropic::claude-sonnet-4-6",
            "OPENROUTER_API_KEY": "",
            "OPENAI_API_KEY": "",
            "OPENAI_BASE_URL": "",
            "OPENAI_COMPATIBLE_API_KEY": "",
            "CLOUDRU_FOUNDATION_MODELS_API_KEY": "",
            "ANTHROPIC_API_KEY": "sk-ant-test",
        }

        fallback_shape = [
            "anthropic::claude-opus-4-6",
            "anthropic::claude-sonnet-4-6",
            "anthropic::claude-sonnet-4-6",
        ]

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models", return_value=fallback_shape),
            patch.object(pr, "_get_review_models", return_value=fallback_shape),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("neila.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertNotIn("at least 2 unique reviewer models", result,
            f"fallback [main, light, light] was rejected as <2 unique: {result[:300]}")
        self.assertNotIn("duplicate reviewer models", result,
            f"server-generated fallback duplicates tripped the "
            f"user-duplicate branch: {result[:300]}")

    async def test_direct_provider_fallback_in_raw_env_does_not_trip_duplicate_gate(self):
        """Real-world failure mode: `apply_runtime_provider_defaults` →
        `_normalize_direct_review_models` writes `[main, light, light]` into
        settings; `apply_settings_to_env` then copies that string into
        `NEILA_REVIEW_MODELS`. On exclusive-direct-provider setups the
        raw env will therefore look like user-authored duplicates.
        `_run_plan_review_async` must not mis-reject this — duplicates in
        raw env are only user-authored when an exclusive direct provider
        is NOT active. Regression for v4.39.0 final-round review Critical #3.
        """
        import os as _os
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()

        # Exact shape `_normalize_direct_review_models` writes into settings
        # for an anthropic-only setup with the shipped defaults.
        fallback_env = (
            "anthropic::claude-opus-4-6,"
            "anthropic::claude-sonnet-4-6,"
            "anthropic::claude-sonnet-4-6"
        )
        fallback_shape = [
            "anthropic::claude-opus-4-6",
            "anthropic::claude-sonnet-4-6",
            "anthropic::claude-sonnet-4-6",
        ]

        env = {
            "NEILA_REVIEW_MODELS": fallback_env,
            "NEILA_MODEL": "anthropic::claude-opus-4-6",
            "NEILA_MODEL_LIGHT": "anthropic::claude-sonnet-4-6",
            "OPENROUTER_API_KEY": "",
            "OPENAI_API_KEY": "",
            "OPENAI_BASE_URL": "",
            "OPENAI_COMPATIBLE_API_KEY": "",
            "CLOUDRU_FOUNDATION_MODELS_API_KEY": "",
            "ANTHROPIC_API_KEY": "sk-ant-test",
        }

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models", return_value=fallback_shape),
            patch.object(pr, "_get_review_models", return_value=fallback_shape),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
            patch.object(pr, "build_full_repo_pack", return_value=("pack", [])),
            patch.object(pr, "build_head_snapshot_section", return_value=""),
            patch("neila.tools.plan_review.estimate_tokens", return_value=10_000),
            patch.object(
                pr, "_query_reviewer",
                return_value={
                    "model": "m", "text": "AGGREGATE: GREEN",
                    "error": None, "tokens_in": 0, "tokens_out": 0,
                },
            ),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertNotIn(
            "duplicate reviewer models", result,
            "Server-generated direct-provider fallback written into env "
            "must not be mis-flagged as user-authored duplicates. "
            f"Got: {result[:400]}",
        )
        self.assertNotIn("at least 2 unique reviewer models", result)

    async def test_openrouter_user_authored_duplicates_still_rejected(self):
        """When no exclusive direct provider is active (OpenRouter key present),
        user-authored duplicates in the raw env MUST still be rejected.
        Guards against the fix to Critical #3 accidentally disabling the
        original duplicate gate."""
        import os as _os
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()

        env = {
            "NEILA_REVIEW_MODELS": "openai/gpt-5.5,openai/gpt-5.5,anthropic/claude-opus-4.6",
            "OPENROUTER_API_KEY": "sk-or-test",
            "OPENAI_API_KEY": "",
            "ANTHROPIC_API_KEY": "",
        }

        with (
            patch.dict(_os.environ, env, clear=False),
            patch.object(_cfg, "get_review_models",
                         return_value=["openai/gpt-5.5", "openai/gpt-5.5",
                                       "anthropic/claude-opus-4.6"]),
            patch.object(pr, "_get_review_models",
                         return_value=["openai/gpt-5.5", "openai/gpt-5.5",
                                       "anthropic/claude-opus-4.6"]),
            patch.object(pr, "_load_plan_checklist", return_value="checklist"),
            patch.object(pr, "_load_bible", return_value=""),
            patch.object(pr, "_load_doc", return_value=""),
        ):
            result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertTrue(result.startswith("ERROR"))
        self.assertIn("duplicate reviewer models", result.lower() + result)

    async def test_explicit_duplicates_under_direct_provider_still_rejected(self):
        """Explicit user-authored duplicates MUST still be rejected even on
        exclusive direct-provider setups — only the AUTO-GENERATED fallback
        shape (`[main, light, light]` or legacy `[main] * N`) is exempted.
        Regression for the final-round Critical #1: the earlier "skip check
        when direct-provider is active" heuristic was too broad and let
        genuinely misconfigured lists slip through.
        """
        import os as _os
        from neila.tools import plan_review as pr
        from neila import config as _cfg

        ctx = _make_ctx()

        # User-authored duplicate list under an Anthropic-only setup.
        # The duplicate `anthropic::a` does NOT match the fallback shape
        # `[anthropic::claude-opus-4-6, anthropic::claude-sonnet-4-6,
        #  anthropic::claude-sonnet-4-6]` that
        # `direct_provider_review_models_fallback` would emit, so the gate
        # must still fire.
        user_duplicates = (
            "anthropic::claude-test-a,"
            "anthropic::claude-test-a,"
            "anthropic::claude-test-b"
        )
        env = {
            "NEILA_REVIEW_MODELS": user_duplicates,
            "NEILA_MODEL": "anthropic::claude-opus-4-6",
            "NEILA_MODEL_LIGHT": "anthropic::claude-sonnet-4-6",
            "OPENROUTER_API_KEY": "",
            "OPENAI_API_KEY": "",
            "OPENAI_BASE_URL": "",
            "OPENAI_COMPATIBLE_API_KEY": "",
            "CLOUDRU_FOUNDATION_MODELS_API_KEY": "",
            "ANTHROPIC_API_KEY": "sk-ant-test",
        }

        with patch.dict(_os.environ, env, clear=False):
            # get_review_models / _get_review_models do not need to be
            # patched — the duplicate check fires from the raw env string
            # before either is consulted. This is exactly the branch we
            # want to regression-guard.
            with (
                patch.object(pr, "_load_plan_checklist", return_value="checklist"),
                patch.object(pr, "_load_bible", return_value=""),
                patch.object(pr, "_load_doc", return_value=""),
            ):
                result = await pr._run_plan_review_async(ctx, "plan", "goal", [])

        self.assertTrue(
            result.startswith("ERROR"),
            f"User-authored duplicates under direct-provider setup were "
            f"accepted; expected the duplicate gate to fire. Got: {result[:400]}",
        )
        self.assertIn("duplicate reviewer models", result)
        self.assertIn("anthropic::claude-test-a", result)


if __name__ == "__main__":
    unittest.main()


